/** Les neuf services de CONCEPTION §87. */
export { ContentService } from './ContentService';
export type { LoadedContent } from './ContentService';
export { ContentUpdateService } from './ContentUpdateService';
export { StorageService } from './StorageService';
export type { StorageReport } from './StorageService';
export { SaveService } from './SaveService';
export { SyncService } from './SyncService';
export { AssetService } from './AssetService';
export { AudioService } from './AudioService';
export type { AudioState } from './AudioService';
export { VoiceRecorderService, MicrophoneError, IMPORT_ACCEPT, IMPORTABLE_EXTENSIONS } from './VoiceRecorderService';
export type { MicPermission, RecordingTake, StoredTake } from './VoiceRecorderService';
export { AuthService } from './AuthService';
export { MigrationService } from './MigrationService';
export type { MigrationResult } from './MigrationService';
export { SitePublishService, SITE_BUNDLE_PATH } from './SitePublishService';
export type { GitHubTarget, SitePublishResult } from './SitePublishService';
export { ReleaseService } from './ReleaseService';
export type { PublishResult } from './ReleaseService';
export { getBackend, setBackend, localBackend, LOCAL_ADMIN_CODE } from './backends';
export type { Backend, AdminCredentials, DraftMeta, SessionUser, UserRole, MediaRecordMeta } from './backends';
