import type { Creature } from '../types';

/**
 * CREATURES DE LA V1 (CONCEPTION §121 : 15 a 20).
 *
 * Ce sont des creations ORIGINALES : aucun asset sous copyright n'entre dans
 * ce depot. Chaque creature porte un descripteur `visual` a partir duquel
 * `CreatureSprite` dessine une illustration en SVG. L'administrateur peut
 * remplacer nom, description et image depuis /admin (§91).
 *
 * `syllables` sert aux exercices de lecture ET aux quetes (« trouve une
 * creature avec trois syllabes », §25).
 */
export const defaultCreatures: Creature[] = [
  /* ------------------------------ PRAIRIE ------------------------------ */
  {
    id: 'piloupi',
    name: 'Piloupi',
    nameEn: 'Fluffle',
    type1: 'NORMAL',
    rarity: 'COMMON',
    biomes: ['prairie'],
    habitat: 'Prairie des Premiers Pas',
    syllables: ['Pi', 'lou', 'pi'],
    colorKey: 'jaune',
    description: 'Une petite boule de duvet qui suit les enfants curieux.',
    visual: {
      shape: 'round',
      palette: ['#FFD45C', '#FFE9A2'],
      accent: '#FF9E7A',
      ears: 'round',
      eyes: 'happy',
      feature: 'none',
    },
  },
  {
    id: 'zibulle',
    name: 'Zibulle',
    nameEn: 'Zappy',
    type1: 'ELECTRIK',
    rarity: 'COMMON',
    biomes: ['prairie'],
    habitat: 'Prairie des Premiers Pas',
    syllables: ['Zi', 'bulle'],
    colorKey: 'jaune',
    description: 'Elle crépite doucement quand elle est contente.',
    visual: {
      shape: 'blob',
      palette: ['#FFD45C', '#FFF8EC'],
      accent: '#FF777F',
      ears: 'pointy',
      eyes: 'dot',
      feature: 'spark',
    },
  },
  {
    id: 'moustiflor',
    name: 'Moustiflor',
    nameEn: 'Blossly',
    type1: 'PLANTE',
    rarity: 'COMMON',
    biomes: ['prairie'],
    habitat: 'Prairie des Premiers Pas',
    syllables: ['Mous', 'ti', 'flor'],
    colorKey: 'rose',
    description: 'Une fleur qui marche et qui sent très bon.',
    visual: {
      shape: 'round',
      palette: ['#FFB0B5', '#FFE9A2'],
      accent: '#A8D86E',
      ears: 'none',
      eyes: 'happy',
      feature: 'leaf',
    },
  },
  {
    id: 'herbibou',
    name: 'Herbibou',
    nameEn: 'Leafowl',
    type1: 'PLANTE',
    type2: 'VOL',
    rarity: 'UNCOMMON',
    biomes: ['prairie', 'foret'],
    habitat: 'Lisière de la Forêt',
    syllables: ['Her', 'bi', 'bou'],
    colorKey: 'vert',
    description: 'Il dort le jour, perché sur les hautes herbes.',
    visual: {
      shape: 'bird',
      palette: ['#A8D86E', '#D6EDB6'],
      accent: '#FFD45C',
      ears: 'pointy',
      eyes: 'sleepy',
      feature: 'wing',
    },
  },
  {
    id: 'ventoline',
    name: 'Ventoline',
    nameEn: 'Breezle',
    type1: 'VOL',
    rarity: 'UNCOMMON',
    biomes: ['prairie'],
    habitat: 'Prairie des Premiers Pas',
    syllables: ['Ven', 'to', 'line'],
    colorKey: 'blanc',
    description: 'On la voit surtout les jours de vent.',
    visual: {
      shape: 'bird',
      palette: ['#FFFDF9', '#D7D9FF'],
      accent: '#62D7D0',
      ears: 'long',
      eyes: 'big',
      feature: 'wing',
    },
  },

  /* ------------------------------- FORET ------------------------------- */
  {
    id: 'feuillou',
    name: 'Feuillou',
    nameEn: 'Leafy',
    type1: 'PLANTE',
    rarity: 'COMMON',
    biomes: ['foret'],
    habitat: 'Forêt de Jade',
    syllables: ['Feuil', 'lou'],
    colorKey: 'vert',
    description: 'Il se cache sous les feuilles mortes.',
    visual: {
      shape: 'blob',
      palette: ['#A8D86E', '#D6EDB6'],
      accent: '#514A4B',
      ears: 'none',
      eyes: 'happy',
      feature: 'leaf',
    },
  },
  {
    id: 'noizette',
    name: 'Noizette',
    nameEn: 'Nutty',
    type1: 'PLANTE',
    type2: 'NORMAL',
    rarity: 'COMMON',
    biomes: ['foret'],
    habitat: 'Forêt de Jade',
    syllables: ['Noi', 'zette'],
    colorKey: 'marron',
    description: 'Elle cache des noisettes partout et les oublie.',
    visual: {
      shape: 'quad',
      palette: ['#E0C48C', '#FFF8EC'],
      accent: '#A8D86E',
      ears: 'round',
      eyes: 'dot',
      feature: 'leaf',
    },
  },
  {
    id: 'chamouss',
    name: 'Chamouss',
    nameEn: 'Mossling',
    type1: 'NORMAL',
    rarity: 'UNCOMMON',
    biomes: ['foret'],
    habitat: 'Forêt de Jade',
    syllables: ['Cha', 'mouss'],
    colorKey: 'marron',
    description: 'Sa fourrure est douce comme de la mousse.',
    visual: {
      shape: 'quad',
      palette: ['#C9B79C', '#FFF8EC'],
      accent: '#A8D86E',
      ears: 'pointy',
      eyes: 'happy',
      feature: 'none',
    },
  },
  {
    id: 'lianou',
    name: 'Lianou',
    nameEn: 'Vinely',
    type1: 'PLANTE',
    rarity: 'RARE',
    biomes: ['foret'],
    habitat: 'Cœur de la Forêt',
    syllables: ['Lia', 'nou'],
    colorKey: 'vert',
    description: 'Il se balance de branche en branche sans bruit.',
    visual: {
      shape: 'serpent',
      palette: ['#A8D86E', '#62D7D0'],
      accent: '#FFD45C',
      ears: 'none',
      eyes: 'big',
      feature: 'leaf',
    },
  },
  {
    id: 'papilune',
    name: 'Papilune',
    nameEn: 'Moonwing',
    type1: 'INSECTE',
    type2: 'VOL',
    rarity: 'RARE',
    biomes: ['foret'],
    habitat: 'Cœur de la Forêt',
    syllables: ['Pa', 'pi', 'lune'],
    colorKey: 'rose',
    description: 'Ses ailes brillent doucement au clair de lune.',
    visual: {
      shape: 'bird',
      palette: ['#D7B5F5', '#FFC1DE'],
      accent: '#FFFDF9',
      ears: 'long',
      eyes: 'happy',
      feature: 'wing',
    },
  },

  /* ------------------------------ RIVIERE ------------------------------ */
  {
    id: 'goutlin',
    name: 'Goutlin',
    nameEn: 'Dropling',
    type1: 'EAU',
    rarity: 'COMMON',
    biomes: ['riviere'],
    habitat: 'Rivière Claire',
    syllables: ['Gout', 'lin'],
    colorKey: 'bleu',
    description: 'Une goutte joueuse qui rebondit sur les cailloux.',
    visual: {
      shape: 'blob',
      palette: ['#7FC4F5', '#BDEDEA'],
      accent: '#FFFDF9',
      ears: 'none',
      eyes: 'happy',
      feature: 'fin',
    },
  },
  {
    id: 'nageo',
    name: 'Nagéo',
    nameEn: 'Swimmo',
    type1: 'EAU',
    rarity: 'COMMON',
    biomes: ['riviere'],
    habitat: 'Rivière Claire',
    syllables: ['Na', 'gé', 'o'],
    colorKey: 'bleu',
    description: 'Il remonte la rivière à toute vitesse.',
    visual: {
      shape: 'serpent',
      palette: ['#62D7D0', '#BDEDEA'],
      accent: '#919AEF',
      ears: 'fin',
      eyes: 'dot',
      feature: 'fin',
    },
  },
  {
    id: 'crapotin',
    name: 'Crapotin',
    nameEn: 'Hoppy',
    type1: 'EAU',
    rarity: 'COMMON',
    biomes: ['riviere'],
    habitat: 'Rivière Claire',
    syllables: ['Cra', 'po', 'tin'],
    colorKey: 'vert',
    description: 'Il saute d’un nénuphar à l’autre en chantant.',
    visual: {
      shape: 'quad',
      palette: ['#A8D86E', '#BDEDEA'],
      accent: '#FFD45C',
      ears: 'none',
      eyes: 'big',
      feature: 'fin',
    },
  },
  {
    id: 'cascadin',
    name: 'Cascadin',
    nameEn: 'Splashy',
    type1: 'EAU',
    rarity: 'UNCOMMON',
    biomes: ['riviere'],
    habitat: 'Petite Cascade',
    syllables: ['Cas', 'ca', 'din'],
    colorKey: 'bleu',
    description: 'On l’entend avant de le voir.',
    visual: {
      shape: 'round',
      palette: ['#919AEF', '#BDEDEA'],
      accent: '#FFFDF9',
      ears: 'fin',
      eyes: 'happy',
      feature: 'fin',
    },
  },
  {
    id: 'brumo',
    name: 'Brumo',
    nameEn: 'Misty',
    type1: 'EAU',
    type2: 'GLACE',
    rarity: 'UNCOMMON',
    biomes: ['riviere'],
    habitat: 'Petite Cascade',
    syllables: ['Bru', 'mo'],
    colorKey: 'blanc',
    description: 'Il apparaît dans la brume du matin.',
    visual: {
      shape: 'blob',
      palette: ['#FFFDF9', '#BDEDEA'],
      accent: '#62D7D0',
      ears: 'none',
      eyes: 'sleepy',
      feature: 'snow',
    },
  },

  /* ------------------------- CHEMIN DE PIERRE -------------------------- */
  {
    id: 'rocaillou',
    name: 'Rocaillou',
    nameEn: 'Pebbly',
    type1: 'ROCHE',
    rarity: 'COMMON',
    biomes: ['grotte'],
    habitat: 'Chemin des Pierres',
    syllables: ['Ro', 'cail', 'lou'],
    colorKey: 'gris',
    description: 'Il ressemble à un caillou… jusqu’à ce qu’il cligne des yeux.',
    visual: {
      shape: 'rock',
      palette: ['#C9B79C', '#E0C48C'],
      accent: '#837B7A',
      ears: 'none',
      eyes: 'dot',
      feature: 'rock',
    },
  },
  {
    id: 'silexo',
    name: 'Silexo',
    nameEn: 'Flinty',
    type1: 'ROCHE',
    rarity: 'UNCOMMON',
    biomes: ['grotte'],
    habitat: 'Chemin des Pierres',
    syllables: ['Si', 'le', 'xo'],
    colorKey: 'marron',
    description: 'Ses arêtes font des étincelles quand il court.',
    visual: {
      shape: 'rock',
      palette: ['#E0C48C', '#FFE9A2'],
      accent: '#FF9E7A',
      ears: 'pointy',
      eyes: 'dot',
      feature: 'rock',
    },
  },
  {
    id: 'granitou',
    name: 'Granitou',
    nameEn: 'Granith',
    type1: 'ROCHE',
    type2: 'SOL',
    rarity: 'UNCOMMON',
    biomes: ['grotte'],
    habitat: 'Grotte de Pierre',
    syllables: ['Gra', 'ni', 'tou'],
    colorKey: 'gris',
    description: 'Le plus calme de tous. Il dort debout.',
    visual: {
      shape: 'rock',
      palette: ['#837B7A', '#C9B79C'],
      accent: '#FFD45C',
      ears: 'none',
      eyes: 'sleepy',
      feature: 'rock',
    },
  },
  {
    id: 'volcanou',
    name: 'Volcanou',
    nameEn: 'Emberock',
    type1: 'FEU',
    type2: 'ROCHE',
    rarity: 'RARE',
    biomes: ['grotte'],
    habitat: 'Grotte de Pierre',
    syllables: ['Vol', 'ca', 'nou'],
    colorKey: 'rouge',
    description: 'Une petite braise vit au creux de sa pierre.',
    visual: {
      shape: 'rock',
      palette: ['#FF9E7A', '#FF777F'],
      accent: '#FFD45C',
      ears: 'none',
      eyes: 'big',
      feature: 'flame',
    },
  },
  {
    id: 'cristalin',
    name: 'Cristalin',
    nameEn: 'Crystalis',
    type1: 'GLACE',
    type2: 'ROCHE',
    rarity: 'VERY_RARE',
    biomes: ['grotte', 'riviere'],
    habitat: 'Grotte de Pierre',
    syllables: ['Cris', 'ta', 'lin'],
    colorKey: 'blanc',
    description: 'On raconte qu’il ne se montre qu’aux dresseurs patients.',
    visual: {
      shape: 'rock',
      palette: ['#BDEDEA', '#D7D9FF'],
      accent: '#FFFDF9',
      ears: 'pointy',
      eyes: 'big',
      feature: 'snow',
    },
  },
];
