import type { ExerciseAudio, ExerciseTemplate } from '../types';

/**
 * MATRICES D'EXERCICES DE LA V1 (CONCEPTION §31-32).
 *
 * Une matrice ne decrit PAS un exercice : elle decrit une famille d'exercices.
 * `count-easy` produit a lui seul des centaines d'instances differentes selon
 * le seed et la creature tiree.
 *
 * Les consignes sont volontairement GENERIQUES (§57) : « Combien vois-tu de
 * créatures ? » fonctionne quelle que soit la creature affichee, donc une
 * seule voix enregistree suffit pour toute la matrice.
 */

/** Convention de nommage des voix d'exercice (§54-55). */
function audioFor(id: string): ExerciseAudio {
  return {
    question: { voiceId: `voice.ex.${id}.q` },
    hint1: { voiceId: `voice.ex.${id}.h1` },
    hint2: { voiceId: `voice.ex.${id}.h2` },
    success: { voiceId: `voice.ex.${id}.ok` },
  };
}

export const defaultExerciseTemplates: ExerciseTemplate[] = [
  /* --------------------------- COUNT (V1) --------------------------- */
  {
    id: 'count-easy',
    type: 'COUNT',
    label: 'Compter jusqu’à 5',
    category: 'MATH',
    skillId: 'math.counting',
    difficulty: 1,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Combien vois-tu de créatures ?',
    hint1Text: 'Compte-les doucement, une par une.',
    hint2Text: 'On les compte ensemble : je te montre les bonnes réponses.',
    successText: 'Bravo ! Tu as bien compté !',
    audio: audioFor('count-easy'),
    minValue: 2,
    maxValue: 5,
  },
  {
    id: 'count-medium',
    type: 'COUNT',
    label: 'Compter jusqu’à 8',
    category: 'MATH',
    skillId: 'math.counting',
    difficulty: 2,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Combien vois-tu de créatures ?',
    hint1Text: 'Touche-les du doigt en comptant.',
    hint2Text: 'Regarde bien : il n’en reste que deux possibles.',
    successText: 'Super ! C’était bien ça !',
    audio: audioFor('count-medium'),
    minValue: 4,
    maxValue: 8,
  },
  {
    id: 'count-hard',
    type: 'COUNT',
    label: 'Compter jusqu’à 12',
    category: 'MATH',
    skillId: 'math.counting',
    difficulty: 3,
    answerCount: 4,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Combien vois-tu de créatures ?',
    hint1Text: 'Compte par petits groupes.',
    hint2Text: 'Je t’aide : il n’en reste que deux.',
    successText: 'Bravo ! Tu comptes très bien !',
    audio: audioFor('count-hard'),
    minValue: 7,
    maxValue: 12,
  },

  /* --------------------- MATCH_IMAGE_WORD (V1) ---------------------- */
  {
    id: 'match-image-word-easy',
    type: 'MATCH_IMAGE_WORD',
    label: 'Image → mot',
    category: 'READING',
    skillId: 'reading.words',
    difficulty: 1,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Quel est son nom ?',
    hint1Text: 'Regarde la première lettre du mot.',
    hint2Text: 'Il n’en reste que deux : écoute bien.',
    successText: 'Bravo ! C’est bien son nom !',
    audio: audioFor('match-image-word-easy'),
    direction: 'imageToWord',
  },
  {
    id: 'match-image-word-word',
    type: 'MATCH_IMAGE_WORD',
    label: 'Mot → image',
    category: 'READING',
    skillId: 'reading.words',
    difficulty: 2,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Touche la créature qui s’appelle comme ça.',
    hint1Text: 'Lis le mot syllabe par syllabe.',
    hint2Text: 'Il n’en reste que deux : regarde bien.',
    successText: 'Bravo ! Tu as bien lu !',
    audio: audioFor('match-image-word-word'),
    direction: 'wordToImage',
  },
  {
    id: 'choose-word-easy',
    type: 'CHOOSE_WORD',
    label: 'Choisir le bon mot',
    category: 'READING',
    skillId: 'reading.words',
    difficulty: 2,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Quel mot va avec cette créature ?',
    hint1Text: 'Les mots se ressemblent : regarde le début.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('choose-word-easy'),
    distractors: 'sameFirstLetter',
  },

  /* --------------------- MISSING_LETTER (V1) ------------------------ */
  {
    id: 'missing-letter-first',
    type: 'MISSING_LETTER',
    label: 'Première lettre',
    category: 'READING',
    skillId: 'reading.letters',
    difficulty: 1,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Quelle lettre manque au début ?',
    hint1Text: 'Écoute le début du mot.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo ! C’est la bonne lettre !',
    audio: audioFor('missing-letter-first'),
    position: 'first',
  },
  {
    id: 'missing-letter-any',
    type: 'MISSING_LETTER',
    label: 'Lettre manquante',
    category: 'READING',
    skillId: 'reading.letters',
    difficulty: 2,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Quelle lettre manque ?',
    hint1Text: 'Relis le mot lettre par lettre.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo ! Le mot est complet !',
    audio: audioFor('missing-letter-any'),
    position: 'any',
  },
  {
    id: 'missing-letter-last',
    type: 'MISSING_LETTER',
    label: 'Dernière lettre',
    category: 'READING',
    skillId: 'reading.letters',
    difficulty: 2,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Quelle lettre manque à la fin ?',
    hint1Text: 'Écoute la fin du mot.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('missing-letter-last'),
    position: 'last',
  },

  /* --------------------------- SYLLABE ------------------------------ */
  {
    id: 'syllable-count',
    type: 'SYLLABLE',
    label: 'Compter les syllabes',
    category: 'READING',
    skillId: 'reading.syllables',
    difficulty: 2,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Combien y a-t-il de syllabes ?',
    hint1Text: 'Tape dans tes mains à chaque syllabe.',
    hint2Text: 'Regarde : je sépare les syllabes.',
    successText: 'Bravo ! Tu entends bien les syllabes !',
    audio: audioFor('syllable-count'),
    mode: 'countSyllables',
  },
  {
    id: 'syllable-first',
    type: 'SYLLABLE',
    label: 'Première syllabe',
    category: 'READING',
    skillId: 'reading.syllables',
    difficulty: 3,
    answerCount: 3,
    hintType: 'splitSyllables',
    creaturePool: { kind: 'random' },
    prompt: 'Par quelle syllabe commence son nom ?',
    hint1Text: 'Écoute bien le tout début.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('syllable-first'),
    mode: 'pickFirstSyllable',
  },

  /* --------------------------- REPERAGE (V1) ------------------------ */
  {
    id: 'left-easy',
    type: 'LEFT_RIGHT',
    label: 'À gauche',
    category: 'SPATIAL',
    skillId: 'spatial.leftRight',
    difficulty: 1,
    answerCount: 2,
    hintType: 'highlightDirection',
    creaturePool: { kind: 'random' },
    prompt: 'Touche la créature qui est à gauche.',
    hint1Text: 'La gauche, c’est du côté de ta main qui tient la feuille.',
    hint2Text: 'Regarde la flèche.',
    successText: 'Bravo ! C’était bien à gauche !',
    audio: audioFor('left-easy'),
    axis: 'leftRight',
    target: 'LEFT',
  },
  {
    id: 'right-easy',
    type: 'LEFT_RIGHT',
    label: 'À droite',
    category: 'SPATIAL',
    skillId: 'spatial.leftRight',
    difficulty: 1,
    answerCount: 2,
    hintType: 'highlightDirection',
    creaturePool: { kind: 'random' },
    prompt: 'Touche la créature qui est à droite.',
    hint1Text: 'La droite, c’est de l’autre côté.',
    hint2Text: 'Regarde la flèche.',
    successText: 'Bravo ! C’était bien à droite !',
    audio: audioFor('right-easy'),
    axis: 'leftRight',
    target: 'RIGHT',
  },
  {
    id: 'above-easy',
    type: 'LEFT_RIGHT',
    label: 'Au-dessus',
    category: 'SPATIAL',
    skillId: 'spatial.aboveBelow',
    difficulty: 2,
    answerCount: 2,
    hintType: 'highlightDirection',
    creaturePool: { kind: 'random' },
    prompt: 'Touche la créature qui est au-dessus.',
    hint1Text: 'Au-dessus, c’est en haut.',
    hint2Text: 'Regarde la flèche.',
    successText: 'Bravo !',
    audio: audioFor('above-easy'),
    axis: 'aboveBelow',
    target: 'UP',
  },
  {
    id: 'grid-easy',
    type: 'GRID_MOVE',
    label: 'Suivre un chemin',
    category: 'SPATIAL',
    skillId: 'spatial.grid',
    difficulty: 2,
    answerCount: 3,
    hintType: 'highlightDirection',
    creaturePool: { kind: 'random' },
    prompt: 'Où arrive la créature ?',
    hint1Text: 'Suis les flèches avec ton doigt.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo ! Tu as suivi le chemin !',
    audio: audioFor('grid-easy'),
    gridSize: 3,
    steps: 2,
  },

  /* ---------------------------- NOMBRES ----------------------------- */
  {
    id: 'addition-easy',
    type: 'ADDITION',
    label: 'Additions jusqu’à 5',
    category: 'MATH',
    skillId: 'math.addition',
    difficulty: 2,
    answerCount: 3,
    hintType: 'showObjects',
    creaturePool: { kind: 'random' },
    prompt: 'Combien y en a-t-il en tout ?',
    hint1Text: 'Compte d’abord le premier groupe, puis continue.',
    hint2Text: 'Je te montre les créatures : compte-les toutes.',
    successText: 'Bravo ! Tu sais additionner !',
    audio: audioFor('addition-easy'),
    maxTerm: 3,
    maxSum: 5,
    showObjects: true,
  },
  {
    id: 'addition-medium',
    type: 'ADDITION',
    label: 'Additions jusqu’à 10',
    category: 'MATH',
    skillId: 'math.addition',
    difficulty: 3,
    answerCount: 3,
    hintType: 'showObjects',
    creaturePool: { kind: 'random' },
    prompt: 'Combien y en a-t-il en tout ?',
    hint1Text: 'Pars du plus grand nombre et compte la suite.',
    hint2Text: 'Je te montre les créatures.',
    successText: 'Bravo !',
    audio: audioFor('addition-medium'),
    maxTerm: 6,
    maxSum: 10,
    showObjects: true,
  },
  {
    id: 'subtraction-easy',
    type: 'SUBTRACTION',
    label: 'Soustractions jusqu’à 6',
    category: 'MATH',
    skillId: 'math.subtraction',
    difficulty: 3,
    answerCount: 3,
    hintType: 'showObjects',
    creaturePool: { kind: 'random' },
    prompt: 'Combien en reste-t-il ?',
    hint1Text: 'Enlève-les une par une.',
    hint2Text: 'Je te montre celles qui restent.',
    successText: 'Bravo !',
    audio: audioFor('subtraction-easy'),
    maxValue: 6,
    showObjects: true,
  },
  {
    id: 'compare-more',
    type: 'COMPARE',
    label: 'Le plus grand groupe',
    category: 'MATH',
    skillId: 'math.compare',
    difficulty: 1,
    answerCount: 2,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Où y en a-t-il le plus ?',
    hint1Text: 'Compte chaque groupe.',
    hint2Text: 'Compte-les avec moi, doucement.',
    successText: 'Bravo !',
    audio: audioFor('compare-more'),
    maxValue: 6,
    question: 'more',
  },
  {
    id: 'compare-less',
    type: 'COMPARE',
    label: 'Le plus petit groupe',
    category: 'MATH',
    skillId: 'math.compare',
    difficulty: 2,
    answerCount: 2,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Où y en a-t-il le moins ?',
    hint1Text: 'Compte chaque groupe.',
    hint2Text: 'Compte-les avec moi, doucement.',
    successText: 'Bravo !',
    audio: audioFor('compare-less'),
    maxValue: 6,
    question: 'less',
  },
  {
    id: 'number-next',
    type: 'NUMBER_SEQUENCE',
    label: 'Le nombre suivant',
    category: 'MATH',
    skillId: 'math.sequence',
    difficulty: 2,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Quel nombre vient après ?',
    hint1Text: 'Relis la suite à voix haute.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('number-next'),
    minValue: 1,
    maxValue: 20,
    mode: 'next',
    length: 4,
  },
  {
    id: 'number-previous',
    type: 'NUMBER_SEQUENCE',
    label: 'Le nombre précédent',
    category: 'MATH',
    skillId: 'math.sequence',
    difficulty: 3,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Quel nombre vient avant ?',
    hint1Text: 'Compte à l’envers.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('number-previous'),
    minValue: 2,
    maxValue: 20,
    mode: 'previous',
    length: 4,
  },
  {
    id: 'number-missing',
    type: 'NUMBER_SEQUENCE',
    label: 'Le nombre manquant',
    category: 'MATH',
    skillId: 'math.sequence',
    difficulty: 3,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'Quel nombre manque ?',
    hint1Text: 'Relis la suite dans l’ordre.',
    hint2Text: 'Il n’en reste que deux.',
    successText: 'Bravo !',
    audio: audioFor('number-missing'),
    minValue: 1,
    maxValue: 20,
    mode: 'missing',
    length: 5,
  },

  /* ----------------------------- ANGLAIS ---------------------------- */
  {
    id: 'english-color-blue',
    type: 'ENGLISH_WORD',
    label: 'Touch the blue one',
    category: 'ENGLISH',
    skillId: 'english.basics',
    difficulty: 2,
    answerCount: 3,
    hintType: 'removeWrongAnswer',
    creaturePool: { kind: 'random' },
    prompt: 'Touch the {cible} one!',
    hint1Text: 'Blue, c’est bleu.',
    hint2Text: 'Only two left!',
    successText: 'Well done!',
    audio: audioFor('english-color-blue'),
    locale: 'en-GB',
    mode: 'color',
    color: 'bleu',
  },
  {
    id: 'english-count-three',
    type: 'ENGLISH_WORD',
    label: 'Find three',
    category: 'ENGLISH',
    skillId: 'english.basics',
    difficulty: 2,
    answerCount: 3,
    hintType: 'highlightOneByOne',
    creaturePool: { kind: 'random' },
    prompt: 'How many do you see?',
    hint1Text: 'Count with me: one, two, three…',
    hint2Text: 'Only two left!',
    successText: 'Great job!',
    audio: audioFor('english-count-three'),
    locale: 'en-GB',
    mode: 'count',
    count: 3,
  },
  {
    id: 'english-creature',
    type: 'ENGLISH_WORD',
    label: 'Which one is…',
    category: 'ENGLISH',
    skillId: 'english.basics',
    difficulty: 3,
    answerCount: 3,
    hintType: 'removeWrongAnswer',
    creaturePool: { kind: 'random' },
    prompt: 'Which one is {cible}?',
    hint1Text: 'Listen again.',
    hint2Text: 'Only two left!',
    successText: 'Well done!',
    audio: audioFor('english-creature'),
    locale: 'en-GB',
    mode: 'creature',
  },
];
